### ISSUE TITLE
How to initial the old data?

### ISSUE THREAD

**Issue by archonwang** [Restream/redmine_filters#1]
@nodecarter 
I have much data before I installed the plugin, How to initial the old data?
Thanks.

**Comment by nodecarter** [comment]
Hi @archonwang , you can run rake task:
`rake redmine_filters:update_participants`

**Comment by archonwang** [comment]
@nodecarter , 
I use the command but not worked .or I should add some parameters?

`bundle exec rake redmine_filters:update_participants RAILS_ENV=production`

by the way, could you please update the readme to add the instructions?

**Comment by nodecarter** [comment]
@archonwang , of course you should run rake task in your actual environment.
